# Generated by Django 3.0 on 2019-12-11 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
