# Generated by Django 3.0 on 2019-12-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='pub_date',
        ),
    ]
