# Generated by Django 3.0 on 2019-12-11 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_new_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 14, 4, 46, 955963, tzinfo=utc)),
        ),
    ]
