# Generated by Django 3.0 on 2019-12-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20191212_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
