# Generated by Django 3.0.2 on 2020-01-25 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20191213_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pubdate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
