# Generated by Django 3.0.2 on 2020-01-25 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200125_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pubdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
