# Generated by Django 3.0.2 on 2020-01-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_auto_20200125_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
